### ISSUE TITLE
Implement JWT refresh token

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#16]
As of now, JWTs expire after 30 days and if a user happens to be browsing when a token expires, the app will automatically log the user out, which may result in very strange behavior. JWTs should have a refresh token so that when it expires, the AuthService can retry authentication automatically to get a new token.

## TODO
- [ ] Add one-time-use refresh field to JWT in back
- [ ] Add `jwt_refresh_tokens` table to manage refresh tokens
- If back doesn't refresh tokens automatically:
  - [ ] Return identifiable response for **expired** tokens
  - [ ] Have AuthService (front) hit a refresh endpoint to get a new token, and then retry the failed request automatically
- If back refreshes tokens automatically:
  - [ ] Check for expiration and generate new token automatically
  - [ ] Blacklist old token and old refresh token
  - [ ] Make sure front saves new token and deletes old one

**Comment by juanmbellini** [comment]
Pregunta, para que necesitamos que se devuelva un "identifiable response for **expired** tokens"?
No alcanza con 401 y listo?

**Comment by lipusal** [comment]
No siempre, no necesariamente quieren decir lo mismo.  Además el back no siempre devuelve 403 cuando le mandás autorización válida pero no tenés acceso, no recuerdo cómo era eso. No es absolutamente necesario pero podría pasar que el front haga re-auth cuando no necesita.

Igual, eso sería sólo si el back no va actualizando tokens automáticamente. Me parece más fácil hacer que el back, al leer un JWT, si le queda menos de 1 día por ejemplo, que invalide el viejo, genere uno nuevo y se lo mande al front. Total el front ya está programado para que si en cualquier momento recibe un token nuevo, lo pisa.
